### ISSUE TITLE
[Bug]: Nginx not working in Herd 1.4.2 if Herd.app in /Users/<username>/Applications

### ISSUE THREAD

**Issue by mho22** [beyondcode/herd-community#439]
### Operating system version

macOS Sonoma 14.3.1

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.4.2

### PHP Version

PHP 8.2.16

### Bug description

It seems like Herd.app can't be added into the admin account Applications directory. Even if it is not in a subfolder. 

This works : 

`/Application/Herd.app`

This doesn't work :

`/Users/<username>/Application/Herd.app`

I found several issues based on the subfolder specificity, but nothing with the user specific Applications directory.

Hope this can help improve Herd.

### Relevant log output

```shell
`...SyntaxError: cannot find module "/Applications/Herd.app/Contents/Resources/config/pro/njs/detect.js" in /Users/<username>/Library/Application Support/Herd/config/nginx/:1`
```

**Comment by trych** [comment]
I'm having the same issue and nginx is not runnign at all. This renders Laravel Herd 100% useless for me currently. When I click on the nginx log icon, I get this log:

```
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:80 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:443 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:60 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:80 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:443 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:60 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:80 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:443 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:60 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:80 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:443 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:60 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:80 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:443 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: bind() to 127.0.0.1:60 failed (48: Address already in use)
2024/03/06 15:01:01 [emerg] 1605#11090: still could not bind()
```

Any way to work around this?

**Comment by trych** [comment]
Or even a way to downgrade to the previous version? I do not even find download links for 1.4.1. 😞

**Comment by mpociot** [comment]
@trych this issue is unrelated to the one reported by @mho22 

Please force stop nginx by holding the "option" key when the Herd menu entry is open.
Your issue seems to be a leftover nginx process, as the port is already in use.

**Comment by trych** [comment]
@mpociot Thanks a lot for the quick help. Force stopping nginx worked (although it is kind of confusing to stop something that according to the grey dot is seemingly not running), but after each relaunch (and consecutive automatic start of Laravel Herd) I hit the same issue again and would need to do the Force stop / Restart routine again.

This did not happen at all using 1.4.1, so this must be some newly introduced issue with 1.4.2. Should I open a separate issue about this?

I use fish shell btw if this might be at all related. No idea.

**Comment by sschlein** [comment]
@trych That doesn't solve your problem but I am super keen to know: What makes fish shell appealing to you? I go to their website and it's an instant "no", so I must be clearly missing something.

**Comment by mpociot** [comment]
Yeah exactly. Right now, we assume that Herd is placed in the /Applications root folder and not within a subfolder. 
If you move the app, it'll be fixed 👍

**Comment by cotiga** [comment]
I moved Herd to Applications and edited the (new) correct path in the files:

/Users/ME/Library/Application Support/Herd/config/nginx/nginx.conf
/Users/ME/Library/Application Support/Herd/config/nginx/herd.conf

And everything works again.

Small regret though, with version 1.4.1 Herd worked in an "Applications" subfolder, why suddenly does it no longer work with v1.4.2?
A warning informing us that Herd must be installed at the root of "Applications" would be welcome.

Thanks 4 everything U do

**Comment by mho22** [comment]
@mpociot Just to be sure, you didn't implement the `Users/<username>/Applications` feature in the new release, right ? I tried to install it again when 1.5.0 was released but I still have the same issue.

You completed the bug issue because you don't plan to implement it now, right ?
